"""Output service - business logic layer (simplified for review)"""

from typing import Optional
from sqlalchemy.ext.asyncio import AsyncSession

from app.modules.output.models import Output
from app.modules.output.repository import output_repository
from app.modules.item.repository import item_repository
from app.modules.audit.service import action_log_service
from app.ai.output_service import output_service as mock_output_service
from app.common.enums import (
    OutputStatus, ItemStatus, ActionType, OperatorType, BizType,
)


class OutputService:
    """Output service - business logic layer"""

    async def create(self, db: AsyncSession, item_id: int, output_type: str, analysis_id: Optional[int] = None):
        """Generate Output"""
        from app.core.exceptions import BadRequestException
        
        # Get Item
        item = await item_repository.get_by_id(db, item_id)
        if not item:
            raise BadRequestException(f"Item {item_id} not found")
        
        # Check Item status
        if item.status not in [ItemStatus.DECIDED, ItemStatus.OUTPUT_GENERATED]:
            raise BadRequestException(f"Item must be decided or output_generated. Current: {item.status}")
        
        # Check duplicate
        existing = await output_repository.get_by_item_and_type(db, item_id, output_type)
        if existing:
            raise BadRequestException(f"Output type '{output_type}' already exists for item {item_id}")
        
        # Validate analysis_id if provided
        if analysis_id is not None:
            from app.modules.analysis.repository import analysis_repository
            analysis = await analysis_repository.get_by_id(db, analysis_id)
            if not analysis:
                raise BadRequestException(f"Analysis {analysis_id} not found")
            if analysis.item_id != item_id:
                raise BadRequestException(f"Analysis {analysis_id} does not belong to item {item_id}")
            if analysis.status != "confirmed":
                raise BadRequestException(f"Analysis {analysis_id} is not confirmed")
        
        # Generate content
        mock_result = await mock_output_service.generate(
            output_type=output_type,
            item_raw_input=item.raw_input,
            item_final_title=item.title_final,
        )
        
        # Create Output
        output = await output_repository.create(
            db=db,
            item_id=item_id,
            output_type=output_type,
            title=mock_result["title"],
            content=mock_result["content"],
            summary=mock_result["summary"],
            analysis_id=analysis_id,
        )
        
        # Update Item status if first generation
        from_status = item.status
        if item.status == ItemStatus.DECIDED:
            item = await item_repository.update_status(db, item, ItemStatus.OUTPUT_GENERATED)
            
            # Write action log for Item status change
            await action_log_service.log(
                db=db,
                biz_type=BizType.ITEM,
                biz_id=item.id,
                action_type=ActionType.ITEM_STATUS_CHANGED_TO_OUTPUT_GENERATED,
                operator_type=OperatorType.AI,
                operator_ref="mock_output_service",
                from_status=from_status,
                to_status=ItemStatus.OUTPUT_GENERATED,
                action_payload={"output_id": output.id, "output_type": output_type},
                comment=f"Item status changed to output_generated (first output generated)",
            )
        
        # Write action log for output_generated
        await action_log_service.log(
            db=db,
            biz_type=BizType.OUTPUT,
            biz_id=output.id,
            action_type=ActionType.OUTPUT_GENERATED,
            operator_type=OperatorType.AI,
            operator_ref="mock_output_service",
            from_status=None,
            to_status=OutputStatus.PENDING_CONFIRM,
            action_payload={"item_id": item_id, "output_type": output_type},
            comment=f"Output generated by mock service (type={output_type})",
        )
        
        await db.commit()
        return output

    async def confirm(self, db: AsyncSession, output_id: int):
        """Confirm Output"""
        from app.core.exceptions import BadRequestException
        
        output = await output_repository.get_by_id(db, output_id)
        if not output:
            raise BadRequestException(f"Output {output_id} not found")
        
        if output.status != OutputStatus.PENDING_CONFIRM:
            raise BadRequestException(f"Output is not in pending_confirm status. Current: {output.status}")
        
        # Confirm
        output = await output_repository.confirm(db=db, output=output)
        
        # Write action log
        await action_log_service.log(
            db=db,
            biz_type=BizType.OUTPUT,
            biz_id=output.id,
            action_type=ActionType.OUTPUT_CONFIRMED,
            operator_type=OperatorType.USER,
            operator_ref="user",
            from_status=OutputStatus.PENDING_CONFIRM,
            to_status=OutputStatus.CONFIRMED,
            action_payload={"item_id": output.item_id},
            comment="User confirmed output",
        )
        
        await db.commit()
        return output

    async def adopt(self, db: AsyncSession, output_id: int, adopted_target: str):
        """Adopt Output"""
        from app.core.exceptions import BadRequestException
        
        output = await output_repository.get_by_id_with_item(db, output_id)
        if not output:
            raise BadRequestException(f"Output {output_id} not found")
        
        if output.status != OutputStatus.CONFIRMED:
            raise BadRequestException(f"Output is not in confirmed status. Current: {output.status}")
        
        # Validate adopted_target matches output_type
        valid_target = mock_output_service.get_valid_adopted_target(output.output_type)
        if adopted_target != valid_target:
            raise BadRequestException(
                f"adopted_target '{adopted_target}' does not match output_type '{output.output_type}'. Expected: '{valid_target}'"
            )
        
        # Adopt
        from_status = output.item.status
        output = await output_repository.adopt(db=db, output=output, adopted_target=adopted_target)
        
        # Update Item to done
        item = await item_repository.update_status(db, output.item, ItemStatus.DONE)
        
        # Write action logs
        await action_log_service.log(
            db=db,
            biz_type=BizType.OUTPUT,
            biz_id=output.id,
            action_type=ActionType.OUTPUT_ADOPTED,
            operator_type=OperatorType.USER,
            operator_ref="user",
            from_status=OutputStatus.CONFIRMED,
            to_status=OutputStatus.ADOPTED,
            action_payload={"adopted_target": adopted_target},
            comment=f"User adopted output (target={adopted_target})",
        )
        
        await action_log_service.log(
            db=db,
            biz_type=BizType.ITEM,
            biz_id=output.item.id,
            action_type=ActionType.ITEM_STATUS_CHANGED_TO_DONE,
            operator_type=OperatorType.USER,
            operator_ref="user",
            from_status=from_status,
            to_status=ItemStatus.DONE,
            action_payload={"output_id": output.id},
            comment="Item status changed to done (output adopted)",
        )
        
        await db.commit()
        return output


output_service_obj = OutputService()
